import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main>
					<header className="flex flex-row items-center w-full bg-white">
						<div>
							<Image
								src="/logo-v2.png"
								alt="Atomic Lab"
								width={100}
								height={100}
							/>
						</div>
						<Link href="/" className="text-primary text-lg ml-16">
							{" "}
							Projects{" "}
						</Link>
					</header>
				</main>
				<div className="w-full">{children}</div>
			</body>
		</html>
	);
}
